version: '3.7'

services:
  neo4j:
    image: neo4j:3.5.14-enterprise
    container_name: "neo4j"
    volumes:
      - ./plugins:/home/rstudio/plugins
      - ./data:/home/rstudio/data
      - ./import:/home/rstudio/import
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"
      - "NEO4J_AUTH=neo4j/bodhi"
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4JLABS_PLUGINS=["apoc", "graph-algorithms"]
  rstudio:
    image: rocker/tidyverse
    ports:
      - "8787:8787"
    environment:
      - USER=btibert
      - PASSWORD=bodhi
    volumes:
      - ./:/home/rstudio/
    links:
      - neo4j
